### PR TITLE
add UAT service config for asf/opera-rtc-s1-browse

### PR DESCRIPTION
**Pull request by asjohnston-asf**
https://harmony.uat.earthdata.nasa.gov/C1259974840-ASF/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1260014889-ASF&format=image/png should produce three output files:

# `.png` browse image
59e72e542944395cd4ec4fcbb76f13852dadfd3d27460ade67027b0fb498e_rgb

# `.pgw` world file
```
0.0002746662669663458
0.0
0.0
-0.00027461902098253427
-177.46826490379303
69.45012719494066
```

# `.aux.xml` file
```
<PAMDataset>
  <SRS dataAxisToSRSAxisMapping="2,1">GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]</SRS>
  <GeoTransform> -1.7746840223692652e+02,  2.7466626696634580e-04,  0.0000000000000000e+00,  6.9450264504451155e+01,  0.0000000000000000e+00, -2.7461902098253427e-04</GeoTransform>
</PAMDataset>
```

### CODE REVIEW

**Review by chris-durbin — COMMENTED** [review]
I tested successfully locally. You can pull the latest from the harmony main branch to fix the audit issues which were unrelated to your changes.

When I tested in sandbox along with harmony-ci-cd changes, the service failed to download the files from datapool with an SSL issue with certificate and domain mismatches. We'll want to address that first before merging in.

**Comment by asjohnston-asf** [comment]
@bbuechler (cc @mattp0) are you available to work with Chris to diagnose these SSL errors for datapool-test? I'm on leave until Monday. Chris posted additional technical informal in https://bugs.earthdata.nasa.gov/browse/HARMONY-1904

**Comment by asjohnston-asf** [comment]
@jtherrmann can you find more historical documentation on the "private DNS enabled" issue with the API gateway vpc endpoint we encountered last year when trying to invoke an API gateway in a different region? I suspect Chris may be encountering the same issue. 

Here's a pr, but I know there's a ngap or nasd ticket somewhere with more detail:
https://github.com/ASFHyP3/hyp3/pull/1926

**Comment by jtherrmann** [comment]
> @jtherrmann can you find more historical documentation on the "private DNS enabled" issue with the API gateway vpc endpoint we encountered last year when trying to invoke an API gateway in us-west-2 from within earthdata cloud? I suspect Chris may be encountering the same issue.
> 
> Here's a pr, but I know there's a ngap or nasd ticket somewhere with more detail: [ASFHyP3/hyp3#1926](https://github.com/ASFHyP3/hyp3/pull/1926)

I found the two NASD tickets that we created for this issue:

* https://bugs.earthdata.nasa.gov/servicedesk/customer/portal/7/NASD-3691
* https://bugs.earthdata.nasa.gov/servicedesk/customer/portal/7/NASD-3725

The only people with access to those tickets right now are Andrew, Forrest, me, and ASF Data Services.

Here's the summary of our issue that we included in the first ticket:

> Our application in EDC includes an API Gateway exposed to the internet via CloudFront, which meant creating a VPC Endpoint for API Gateway. The VPC Endpoint was configured with "Private DNS names enabled" set to "Yes". Unfortunately, that causes DNS errors for other components in our VPC when making HTTP requests to urls implemented via API Gateway in other AWS accounts.

The solution was to disable the "Private DNS names enabled" setting for the VPC Endpoint.

Here's a link to the AWS docs on "Private REST APIs in API Gateway": https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html

In the first ticket we quote from these docs:

> ...you cannot access public APIs from a VPC by using an API Gateway VPC endpoint with private DNS enabled

(I'm no longer seeing that exact statement on the current version of the docs page, but I'm seeing similar information.)

I think I'm missing the context to assess whether this is the same situation occurring here, but the easiest way to find out would be:

1. Locate the VPC Endpoint for the API Gateway.
2. Disable "Private DNS names enabled" for the VPC Endpoint.

**Comment by asjohnston-asf** [comment]
I'm also getting `{"message":"Internal server error"}` for https://datapool-test.asf.alaska.edu/RTC/OPERA-S1/OPERA_L2_RTC-S1_T001-000659-IW1_20210706T183013Z_20230928T161205Z_S1B_30_v1.0_VV.tif as well this morning. I believe the database behind the datapool-test application was spun down for the weekend as a cost saving measure. I'll check in on it later this morning.

**Comment by asjohnston-asf** [comment]
@chris-durbin datapool-test app is working for me again after the DB got started

**Review by chris-durbin — APPROVED** [review]
Successfully tested out end to end in a harmony sandbox environment. We'll merge in together with the deployment repo PR.

**Pull request merged**
