### PR TITLE
DAS-2255: Adds config and environment for harmony-smap-l2-gridder

### PR DESCRIPTION
**Pull request by flamingbear**
## Jira Issue ID

[DAS-2255](https://bugs.earthdata.nasa.gov/browse/DAS-2255)

## Description

Add Harmony SMAP L2 Gridding Service configuration to Harmony repository.

## Local Test Steps

1. Pull the SMAP docker image from ghcr.io
    `docker pull ghcr.io/nasa/harmony-smap-l2-gridding-service:latest`

1. Update your local Harmony-In-A-Box configuration to include smap-l2-gridder in the `LOCALLY_DEPLOYED_SERVICES`
    `LOCALLY_DEPLOYED_SERVICES=<[blah,blah,etc]>,smap-l2-gridder`

1. start your Harmony-In-A-Box
    `./bin/bootstrap-harmony`

1. Jump onto a NASA VPN.

1. Make a request for a configured collection
     http://localhost:3000/C1263071064-NSIDC_CUAT/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&outputcrs=EPSG%3A4326&format=application%2Fx-netcdf4&maxResults=1

1. Open your workflow-ui and see that it is running the smap-l2-gridder.

1. Visit the job page and download the asset `SMAP_L2_SM_P_E_46849_A_20231108T210834_R19240_003_regridded.nc`

1. Open the file and see that it looks and behaves as expected with xarray or panoply.

## PR Acceptance Checklist
* [X] Acceptance criteria met
* [N/A] Tests added/updated (if needed) and passing
* [N/A] Documentation updated (if needed)
* [X] Harmony in a Box tested? (if changes made to microservices)

### CODE REVIEW

**Comment by flamingbear** [comment]
Setting this as ready for review, heading to the ci-cd repo next.

**Review by indiejames — APPROVED** [review]

**Review by chris-durbin — APPROVED** [review]
Tested successfully in a sandbox environment.

**Comment by D-Auty** [comment]
Is this DAS-2255 or DAS-2254.  The title states DAS-2254, but I suspect should be DAS-2255

**Review by owenlittlejohns — APPROVED** [review]
I think this looks good and the UMM-S record looks good, too.

One quick clarifying question: this is below the Trajectory Subsetter. Will the SMAP L2 collections eventually be hooked up to the Trajectory Subsetter, too? If so, I think this is all okay (the Trajectory Subsetter does not have `reprojection: true` in the capabilities), but I just wanted to bring it up here for consideration before merging and later weird things happening with unexpected services being selected.

**Comment by flamingbear** [comment]
> Will the SMAP L2 collections eventually be hooked up to the Trajectory Subsetter, too?
I think the [collection I'm looking at already has it hooked up in UAT](https://mmt.uat.earthdata.nasa.gov/collections/C1263071064-NSIDC_CUAT).
Screenshot 2024-12-04 at 11 39 43 AM

**Comment by D-Auty** [comment]
Yes, this will eventually all be one chain for Harmony for SMAP L2 data, with GeoTIFF, and reprojection options leading to this service first.  I suspect native NetCDF format output without reprojection could also be linked to this sub-service, but we might leave that out as it is confusing that NetCDF means "Gridded" in this case, not NetCDF formatted original source data.

**Pull request merged**
