### PR TITLE
TRT-411 - Transition production NetCDF-to-Zarr UMM-S to XYZ_PROV.

### PR DESCRIPTION
**Pull request by owenlittlejohns**
## Jira Issue ID

TRT-411

## Description

This PR updates the **production** UMM-S record for the NetCDF-to-Zarr service from one in the POCLOUD provider to one in the XYZ_PROV provider. This aligns with our governance model with the service maintainers (in this case DAS) having control of the UMM-S record representing the service.

A couple of notes:

* I mainly copied the POCLOUD record, but I also have added the `Aggregation` information in the `ServiceOptions`, so that we can indicate the service can concatenate (but not by default). This should now more closely match `services.yml`.
* I will only merge this PR when PO.DAAC are happy that all UMM-C to UMM-S associations using the POCLOUD UMM-S record are replicated with the XYZ_PROV record. (@frankinspace - I can't do that, I think someone with POCLOUD provider rights will need to)

## Local Test Steps

N/A

## PR Acceptance Checklist
* [x] Acceptance criteria met
* ~~Tests added/updated (if needed) and passing~~
* ~~Documentation updated (if needed)~~

### CODE REVIEW

**Review by chris-durbin — APPROVED** [review]

**Review by ygliuvt — APPROVED** [review]

**Comment by owenlittlejohns** [comment]
@frankinspace and @jamesfwood - just a quick nudge here. The specific ask is that all PO.DAAC collections associated with the S2009180097-POCLOUD record are also now associated with S2839491596-XYZ_PROV.

I don't think I can make these associations, as I think the permission to do so stems from having permissions in the collection provider (otherwise, I'd try and take care of this for us).

**Comment by frankinspace** [comment]
Anyone have an easy way to move the associations? @owenlittlejohns ? MMT shows 219 currently associated to S2009180097-POCLOUD. I could maybe write a python script?

**Comment by owenlittlejohns** [comment]
@frankinspace - here's an attempt at a script to do this (GitHub won't let me upload a `.py` file to a comment, so you'll just need to knock off the extra `.txt`)

This isn't tested end-to-end but most of the pieces have been tested in other places individually, so it might need a little bit of tweaking. Hopefully not much, though!

I _think_ all you'll need to do is: pip install `requests`, add a LaunchPad token in the correct place in the file, then:

```
from manage_associations import mirror_service_associations

mirror_service_associations('S2009180097-POCLOUD', 'S2839491596-XYZ_PROV', 'POCLOUD', 'uat', False)
```

[manage_associations.py.txt](https://github.com/nasa/harmony/files/14070117/manage_associations.py.txt)

**Comment by frankinspace** [comment]
@owenlittlejohns I'm checking with our web portal team now but this is what I mentioned during feature planning today: https://podaac.jpl.nasa.gov/dataset/AVHRR18_G-NAVO-L2P-v1.0#capability-modal-service

The datasets listed on our portal create these code snippets dynamically and I believe it is based on umm-c/umm-s associations in cmr (e.g. If collection-a is associated to service-a, then build an example command). If that is true we may need to coordinate an update in our portal while we do this re-association. Apologize for not considering this sooner, I had forgotten about this feature on the portal.

**Comment by owenlittlejohns** [comment]
No problem @frankinspace. One option to go forward might be to create the new associations and leave the old one. Then this change can percolate through the Harmony deployment process (probably taking about a fortnight). The one downside is that in something like EDSC you'd end up seeing two NetCDF-to-Zarr services associated with the collection, but ultimately they would both work. (I think we'd end up with that state during this migration anyway, until we were all comfy removing the old assocations)

**Comment by frankinspace** [comment]
@owenlittlejohns apologize for the delay but I was able to re-associate all POCLOUD collections to the XYZ_PROV umm-s record.

I did notice there was a non-POCLOUD collection (`C2574931653-LARC_ASDC`) associated to `S2009180097-POCLOUD` that I do not have permission to move to the `S2839491596-XYZ_PROV` service

**Comment by owenlittlejohns** [comment]
Thanks, @frankinspace - I'll reach out to someone at ASDC and work out what to do with that other collection. It sounds like once that is resolved we can merge this PR. :tada:

**Comment by owenlittlejohns** [comment]
I've spoken to Hazem at ASDC - the LARC_ASDC collection is no longer associated with the NetCDF-to-Zarr service. I think that means we are good to go. I plan to merge this PR shortly after the CI/CD completes (providing there are no significant failures in the CI/CD that are new from this PR)

**Pull request merged**
