### PR TITLE
HARMONY-1562: Get Giovanni adapter working end to end

### PR DESCRIPTION
**Pull request by chris-durbin**
## Jira Issue ID
HARMONY-1562

## Description
Fixes the Giovanni adapter to work end to end.

## Local Test Steps
Pre-req: Make sure you have the giovanni-adapter included in your `LOCALLY_DEPLOYED_SERVICES`.

1. `npm run build-all-services`
2. `bin/restart-services`
3. http://localhost:3000/C1225808238-GES_DISC/ogc-api-coverages/1.0.0/collections/Grid%2FprecipitationCal/coverage/rangeset?format=text%2Fcsv&point=0.76,-3.8&subset=time(%222020-01-06T12%3A00%3A00Z%22%3A%222020-01-06T16%3A00%3A00Z%22)
4. Click on the job status URL
5. Verify the request is successful and includes a Giovanni link.
6. Click the Giovanni link and log in with EDL if not already logged in.
7. Verify you are redirected to a Giovanni output with precipitation data.

## PR Acceptance Checklist
* [X] Acceptance criteria met
* [X] Tests added/updated (if needed) and passing
* [ ] Documentation updated (if needed)

### CODE REVIEW

**Comment by vinnyinverso** [comment]
I get the giovanni url successfully, but see a 403 when following the URL:
https://api.giovanni.uat.earthdata.nasa.gov/proxy-timeseries?data=GPM_3IMERGHH_06_precipitationCal&location=%5B-3.8%2C0.76%5D&time=2020-01-06T12%3A00%3A00%2F2020-01-06T16%3A00%3A00

**Review by vinnyinverso — APPROVED** [review]

**Comment by vinnyinverso** [comment]
I'll check if there are any EULAs.

**Review by indiejames — APPROVED** [review]
Tested locally

**Comment by chris-durbin** [comment]
> I get the giovanni url successfully, but see a 403 when following the URL: https://api.giovanni.uat.earthdata.nasa.gov/proxy-timeseries?data=GPM_3IMERGHH_06_precipitationCal&location=%5B-3.8%2C0.76%5D&time=2020-01-06T12%3A00%3A00%2F2020-01-06T16%3A00%3A00

I followed that link and EDL redirected back to the content for me.
```
prod_name,GPM_3IMERGHH.06
doi,10.5067/GPM/IMERG/3B-HH/06
param_short_name,precipitationCal
param_name,Multi-satellite precipitation estimate with gauge calibration - Final Run (recommended for general use)
unit,mm/hr
undef,-9.9999e+3
begin_time,2020-01-06 12:00:00
end_time,2020-01-06 16:00:00
lat,-3.85
lon,0.75
lat_resolution,0.1
lon_resolution,0.1
mean,4.1848e-03
Request_time,2023-09-06 17:47:49

Timestamp (UTC),Data
2020-01-06 12:00,0
2020-01-06 12:30,0
2020-01-06 13:00,0.00956448
2020-01-06 13:30,0.01
2020-01-06 14:00,0.00830512
2020-01-06 14:30,0.0058235
2020-01-06 15:00,0.0039702
2020-01-06 15:30,0
2020-01-06 16:00,0
```

**Pull request merged**
