### PR TITLE
DAS-2088 - Update the production Trajectory Subsetter UMM-S record reference.

### PR DESCRIPTION
**Pull request by owenlittlejohns**
## Jira Issue ID

DAS-2088

## Description

This PR updates the UMM-S record used to identify the Trajectory Subsetter in production so that it is one maintained by the Data Services team, who develop the Trajectory Subsetter.

## Local Test Steps

Compare the UMM-S records for the ORNL_CLOUD and XYZ_PROV providers using the following CMR endpoint:

```
https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=<UMM-S concept ID>
```

The important thing is that the service options (e.g., variable/temporal/spatial subsetting) and the Harmony endpoint are consistent. I added some contact information for David and I that were not in the original record.

I will only merge this once all UMM-S to UMM-C associations that exist with the ORNL_CLOUD record are replicated for the XYZ_PROV record. I do not have permission to make those associations, as it requires someone with permissions in the collection providers (ORNL_CLOUD and LARC_ASDC) to do so. I'll solicit help with that, though.

## PR Acceptance Checklist
* [x] Acceptance criteria met
* ~~Tests added/updated (if needed) and passing~~
* ~~Documentation updated (if needed)~~

### CODE REVIEW

**Comment by lyonthefrog** [comment]
I also verified that [cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2836723123-XYZ_PROV](https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2836723123-XYZ_PROV) aligned with [cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2232210365-ORNL_CLOUD](https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2232210365-ORNL_CLOUD.)

**Review by lyonthefrog — APPROVED** [review]
I also verified that 

[cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2836723123-XYZ_PROV](https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2836723123-XYZ_PROV) 

aligns with

[cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2232210365-ORNL_CLOUD](https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S2232210365-ORNL_CLOUD).

**Comment by owenlittlejohns** [comment]
Quick update:

Chris Lindsley at ORNL has added the GEDI L4A association to the new UMM-S record, and the association to the LARC_ASDC collection has been removed from the ORNL_CLOUD UMM-S record. This means that all collections with associations to the ORNL_CLOUD UMM-S record also have associations with this new UMM-S record.

Looking at the failing CI/CD:

* Compare services - this isn't new. I can try and reach out to PO.DAAC and Giovanni metadata curators to reconcile some of these differences.
* Harmony in a box - I'm seeing a `lerna ERR` from `npm run build`. This task is new to me, so I don't know if I've broken anything. (Gut instinct is "no", but I'm biased)
* Snyk - I don't think these are new Snyk findings.

**Comment by chris-durbin** [comment]
> Looking at the failing CI/CD:
> 
> * Compare services - this isn't new. I can try and reach out to PO.DAAC and Giovanni metadata curators to reconcile some of these differences.
I think harmony might have to modify the concatenate settings in services.yml for the Giovanni one
> * Harmony in a box - I'm seeing a `lerna ERR` from `npm run build`. This task is new to me, so I don't know if I've broken anything. (Gut instinct is "no", but I'm biased)
Leo is actively working on this in another PR. Nothing you need to do.
> * Snyk - I don't think these are new Snyk findings.
Agreed

**Review by chris-durbin — APPROVED** [review]

**Comment by owenlittlejohns** [comment]
Okay - based on the comments above (and @chris-durbin approving), I'm going to merge this PR now.

**Pull request merged**
