### PR TITLE
GDDS-67: add GES DISC collections to HOSS

### PR DESCRIPTION
**Pull request by nasajay**
Remove 
C1215802944-GES_DISC
C1225808238-GES_DISC
from GDAL-Subsetter

### CODE REVIEW

**Comment by chris-durbin** [comment]
The title of the PR is to add these collections to HOSS, but right now they are only configured for the ASF GDAL subsetter and netcdf-to-zarr. This PR will make them only available for netcdf-to-zarr. Do you also want to add them to the HOSS subsetter (sds/HOSS in services.yml)?

**Comment by nasajay** [comment]
Thanks Chris. Owen has already submitted another PR:
https://github.com/nasa/harmony/pull/53

**Comment by chris-durbin** [comment]
> Thanks Chris. Owen has already submitted another PR:
> #53

Ah ok - so the UMM-S records have collection associations to the GES_DISC collections. 👍

**Review by chris-durbin — APPROVED** [review]

**Comment by bilts** [comment]
Merging.  I'd recommend GES DISC consider moving over to using UMM-S records to manage their collections in order to make it much easier to add/remove collections from Harmony in the future

**Comment by nasajay** [comment]
Thanks Patrick. Yes we will use UMM-S.

**Pull request merged**
