### PR TITLE
DAS-1939 - Update VAR_SUBSETTER to HOSS.

### PR DESCRIPTION
**Pull request by owenlittlejohns**
## Jira Issue ID

DAS-1939

## Description

This PR does a couple of things...

* Updates Harmony to use the new open source HOSS Docker image (from [GitHub](https://github.com/nasa/harmony-opendap-subsetter/pkgs/container/harmony-opendap-subsetter)).
* Rebrands things from `VAR_SUBSETTER` to `HOSS` (which is hopefully a bit less misleading).

Disclaimer:

I haven't yet published a PR to update the CI/CD repo. I'm not sure if there's a preferred order for merger there, or if we'll just have to skip the build results from the first merger because only having the changes in one place will likely break things?

## Local Test Steps

* Pull this branch.
* Tear down your local Harmony-in-a-box
* In the main directory of the repository run:
```
nvm use
npm i
npm run build-all
./bin/bootstrap-harmony
```
* Try running some requests against HOSS. Probably the best way to do this is to use the [HOSS regression-test suite](https://github.com/nasa/harmony-regression-tests/tree/main/test/hoss), but in the notebook set the `harmony_host_url` variable to `http://localhost:3000`. The requests should get to the correct Docker container, and should complete as expected.

## PR Acceptance Checklist
* [x] Acceptance criteria met
* [x] Tests added/updated (if needed) and passing
* [ ] Documentation updated (if needed)

### CODE REVIEW

**Comment by chris-durbin** [comment]
> I haven't yet published a PR to update the CI/CD repo. I'm not sure if there's a preferred order for merger there, or if we'll just have to skip the build results from the first merger because only having the changes in one place will likely break things?

We test them together, and then when we merge we merge them at the same time. If a build only picks up one of the changes we just cancel the build and use the next build.

**Comment by owenlittlejohns** [comment]
I rebased this branch on top of `main` to get the latest commits just merged (hopefully fixing the Snyk vulnerabilities).

Also, [here is the corresponding Harmony CI/CD pull request](https://git.earthdata.nasa.gov/projects/HARMONY/repos/harmony-ci-cd/pull-requests/222/overview).

**Comment by vinnyinverso** [comment]
Need to update locustfile.py which references var-subsetter (this is for workload test runs).

**Comment by owenlittlejohns** [comment]
I had previously checked the `locustfile.py`, and the request uses a trajectory dataset (ATL08), which uses the UAT service chain that is still the "Variable Subsetter". That said, I don't think this collection is still configured to be used with the Variable Subsetter, so I will find a better collection that is associated with one of the HOSS service chains now. Good catch.

**Review by chris-durbin — APPROVED** [review]
Tested out successfully in my own sandbox along with the harmony-ci-cd changes.

**Review by vinnyinverso — APPROVED** [review]

**Pull request merged**
