### PR TITLE
Harmony 1316

### PR DESCRIPTION
**Pull request by indiejames**
## Jira Issue ID
HARMONY-1316

## Description
Adds filtering by serviceID (as opposed to just jobID) to getting operation for work retrieved by the `getWork` function
for work items.

## Local Test Steps
Add code to log the work item returned by the `getWork` function in `workflow-orchestration.ts` then issue a request to the variable subsetter that includes spatial and variable subsetting:

```
example_request = Request(collection=Collection(id='C1234714698-EEDTEST'),
                          granule_id=['G1238479209-EEDTEST'],
                          variables=['/gt1l/land_segments/dem_h'],
                          spatial=BBox(w=-180, s=-90, e=180, n=90)
``` 

Verify that the `operation` in the work item returned by `getWork` does not include spatial subsetting (the spatial subsetting is only used by the CMR).

## PR Acceptance Checklist
* [x] Acceptance criteria met
* [x] Tests added/updated (if needed) and passing
* [ ] ~Documentation updated (if needed)~

### CODE REVIEW

**Comment by chris-durbin** [comment]
Note that this has implications for any service chains using the `operations` field in services.yml. We'll want to sanity check that all of these work correctly with a request from each one.

**Comment by owenlittlejohns** [comment]
Thanks for such a quick fix! The change looks good to me. I'll test out the example request and I'll dig out some more examples for any other Data Services entries in `services.yml` for testing.

**Comment by owenlittlejohns** [comment]
Here's a request that should cover the NetCDF-to-Zarr service (I ran it locally with this branch and it succeeded):

```
http://localhost:3000/C1233860183-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&granuleId=G1233860548-EEDTEST&format=application%2Fx-zarr&skipPreview=true
```

For the majority of the other services (at least those that we maintain), I'd recommend running through [the SDS_Regression notebook in the regression test repository](https://github.com/nasa/harmony-regression-tests/blob/main/test/sds/SDS_Regression.ipynb) with the `harmony_host_url = 'http://localhost:3000'`. That should cover:

* HOSS (with and without MaskFill step)
* Variable Subsetter
* Trajectory Subsetter
* MaskFill

I ran through that notebook locally on this branch and it took a while, but everything passed.

Other services that have `operations` in `services.yml`, but aren't included in those notebooks:

* Giovanni
* PO.DAAC Level 2 Subsetter.
* PO.DAAC Concise.

**Review by chris-durbin — APPROVED** [review]
I tested out SWOT reprojection, netcdf-to-zarr, the chained SWOT-repr to netcdf-to-zarr, concise, and the PODAAC L2SS to concise chain. Everything worked successfully. It looks like Owen tested out even more so looks good.

**Pull request merged**
