### PR TITLE
HARMONY-897: Add documentation for sharing jobs

### PR DESCRIPTION
**Pull request by vinnyinverso**

### CODE REVIEW

**Review by indiejames — APPROVED** [review]

**Review by chris-durbin — APPROVED** [review]
I think we also need to make providers aware of this change so that they go in and add tag associations for any collections that should allow job sharing. Who is going to contact them and do we have contact info for all of our providers?

For the harmony collections in UAT and Prod, one of us should add the tag associations now.

**Comment by vinnyinverso** [comment]
> I think we also need to make providers aware of this change so that they go in and add tag associations for any collections that should allow job sharing. Who is going to contact them and do we have contact info for all of our providers?
> 
> For the harmony collections in UAT and Prod, one of us should add the tag associations now.

@chris-durbin I can ask Jeanne or Justin for DAAC contact / mailing list unless you have a better idea. 

For associations, I think UAT EED-Test collections are mostly taken care of since we tagged a lot of the Harmony collections for the tests? Which prod collections would we need to associate with the new tag?

I still need to create the harmony.has-eula tag in prod once I have permission.

**Comment by chris-durbin** [comment]
> Which prod collections would we need to associate with the new tag?

C1756916832-XYZ_PROV

**Comment by vinnyinverso** [comment]
> C1756916832-XYZ_PROV

@chris-durbin the tag was created, however, when tagging the above collection, the response was:

```[
  {
    "errors": [
      "Collection [C1756916832-XYZ_PROV] does not exist or is not visible."
    ],
    "tagged_item": {
      "concept_id": "C1756916832-XYZ_PROV"
    }
  }
]```

**Pull request merged**
